import "../main/services.js/usuarios.js";
import "../main/services.js/ubicaciones.js";
import "../main/services.js/respuestas.js";
import "../main/services.js/preguntas.js";
import "../main/services.js/observaciones.js";
import "../main/services.js/indicadores.js";
import "../main/services.js/fuentesAgua.js";
import "../main/services.js/chat.js";
import "../main/services.js/config.js"
import "../main/services.js/centrosAsistencia.js";
import "../main/services.js/calidadAgua.js";
import "../main/services.js/busqueda.js";
import "../main/services.js/biomas.js";
import "../main/services.js/auditorias.js";
import "../main/services.js/reportes.js";
import "../main/services.js/accesibility.js";
import "../main/services.js/signup.js"
import "../main/services.js/login.js";
import "../main/menu.js";